export const airports = [
  {
    name: "Peterborough Airport",
    code: "PBO",
    cities: ["Peterborough"],
    isPopular: true,
  },
  {
    name: "Glasgow Airport",
    code: "GLA",
    cities: ["Glasgow"],
    isPopular: false,
  },
  {
    name: "Heathrow Airport",
    code: "LHR",
    cities: ["London"],
    isPopular: false,
  },
  {
    name: "Manchester Airport",
    code: "MAN",
    cities: ["Manchester"],
    isPopular: false,
  },
  {
    name: "Birmingham Airport",
    code: "BHX",
    cities: ["Birmingham"],
    isPopular: false,
  },
  {
    name: "Edinburgh Airport",
    code: "EDI",
    cities: ["Edinburgh"],
    isPopular: false,
  },
  {
    name: "Bristol Airport",
    code: "BRS",
    cities: ["Bristol"],
    isPopular: false,
  },
  {
    name: "Liverpool John Lennon Airport",
    code: "LPL",
    cities: ["Liverpool"],
    isPopular: false,
  },
  {
    name: "Newcastle Airport",
    code: "NCL",
    cities: ["Newcastle"],
    isPopular: false,
  },
  {
    name: "London City Airport",
    code: "LCY",
    cities: ["London"],
    isPopular: true,
  },
  {
    name: "London Stansted Airport",
    code: "STN",
    cities: ["London"],
    isPopular: true,
  },
  {
    name: "Leeds Bradford Airport",
    code: "LBA",
    cities: ["Leeds"],
    isPopular: false,
  },
];

export const regions = [
  "Peterborough Airport",
  "Glasgow",
  "Greater London",
  "Manchester",
  "Birmingham",
  "Liverpool",
  "Edinburgh",
  "Glasgow",
  "Bristol",
  "Leeds",
  "Sheffield",
  "Newcastle",
  "Cardiff",
  "Oxford",
  "Cambridge",
];
