export const airports = [
  {
    name: "Peterborough Airport",
    code: "PBO",
    cities: ["Peterborough"],
    isPopular: true,
  },
  {
    name: "Glasgow Airport",
    code: "GLA",
    cities: ["Glasgow"],
    isPopular: false,
  },
  {
    name: "Heathrow Airport",
    code: "LHR",
    cities: ["London"],
    isPopular: true,
  },
  {
    name: "Manchester Airport",
    code: "MAN",
    cities: ["Manchester"],
    isPopular: false,
  },
  {
    name: "London Luton Airport",
    code: "LTN",
    cities: ["London"],
    isPopular: true,
  },
  
  {
    name: "Edinburgh Airport",
    code: "EDI",
    cities: ["Edinburgh"],
    isPopular: false,
  },
  {
    name: "Bristol Airport",
    code: "BRS",
    cities: ["Bristol"],
    isPopular: false,
  },
  {
    name: "Liverpool John Lennon Airport",
    code: "LPL",
    cities: ["Liverpool"],
    isPopular: false,
  },
 
  {
    name: "London Gatwick Airport",
    code: "LGW",
    cities: ["London"],
    isPopular: true,
  },
  {
    name: "London City Airport",
    code: "LCY",
    cities: ["London"],
    isPopular: true,
  },
  {
    name: "London Stansted Airport",
    code: "STN",
    cities: ["London"],
    isPopular: true,
  },
  {
    name: "Leeds Bradford Airport",
    code: "LBA",
    cities: ["Leeds"],
    isPopular: false,
  },
  {
    name: "Newcastle Airport",
    code: "NCL",
    cities: ["Newcastle"],
    isPopular: false,
  },
  {
    name: "Birmingham Airport",
    code: "BHX",
    cities: ["Birmingham"],
    isPopular: false,
  },
  {
    name: "East Midlands Airport",
    code: "EMA",
    cities: ["Nottingham", "Leicester", "Derby"],
    isPopular: true,
  },
  {
    name: "Aberdeen Airport",
    code: "ABZ",
    cities: ["Aberdeen"],
    isPopular: false,
  },
  {
    name: "Cardiff Airport",
    code: "CWL",
    cities: ["Cardiff"],
    isPopular: false,
  },
];


export const regions = [
  "Peterborough Airport",
  "Glasgow",
  "Greater London",
  "Manchester",
  "Birmingham",
  "Liverpool",
  "Edinburgh",
  "Bristol",
  "Leeds",
  "Sheffield",
  "Newcastle",
  "Cardiff",
  "Oxford",
  "Cambridge",
  "Leicester",
  "Northampton",
  "Lincoln",
  "Norwich",
  "Nottingham",
  "Bedford",
  "Milton Keynes",
  "Stamford",
  "Huntingdon",
  "Spalding",
  "Wisbech",
  "Grantham",
  "Kettering",
  "Oakham",
  "Bourne",
  "Sleaford",
  "Newark-on-Trent",
  "Holbeach",
  "March",
  "Downham Market",
  "King’s Lynn",
  "Thetford"
];
