export const vehiclesData = [
  {
    id: 1,
    name: "Saloon Car",
    image: "/saloonCar.png",
    passengerCapacity: 4,
    luggageCapacity: 3,
    price: "16£",
  },
  {
    id: 2,
    name: "Executive Car",
    image: "/executiveCar.png",
    passengerCapacity: 4,
    luggageCapacity: 3,
    price: "20£",
  },
  {
    id: 3,
    name: "Estate Car",
    image: "/Estate.png",
    passengerCapacity: 4,
    luggageCapacity: 4,
    price: "35£",
  },
  {
    id: 4,
    name: "SUV",
    image: "/SUV.png",
    passengerCapacity: 4,
    luggageCapacity: 4,
    price: "40£",
  },
  {
    id: 5,
    name: "People Carrier",
    image: "/peoplecarrier.png",
    passengerCapacity: 6,
    luggageCapacity: 5,
    price: "50£",
  },
  {
    id: 6,
    name: "Executive Carrier",
    image: "/executivePeopleCarrier.png",
    passengerCapacity: 5,
    luggageCapacity: 5,
    price: "55£",
  },
  {
    id: 7,
    name: "8 Seater Minibus",
    image: "/minibus.png",
    passengerCapacity: 8,
    luggageCapacity: 8,
    price: "60£",
  },
];