export const rideData = [
  {
    date: "12 March 2024",
    time: "14:30",
    price: "150 £",
    from: "221B Baker Street, Marylebone, London",
    to: "Heathrow Airport, Longford, Hounslow, TW6 1EW",
    vehicle: {
      name: "Standard Taxi",
      passengers: 4,
      luggage: 2,
      image: "/ride-history-car.png",
      reviewStars: 4,
    },
    returnSchedule: {
      date: "13 March 2024",
      time: "10:00",
    },
    status: "Pending",
    // status: "Completed",
  },
  {
    date: "05 April 2024",
    time: "11:15",
    price: "240 £",
    from: "Piccadilly Station, Manchester, M1 2QF",
    to: "Liverpool John Lennon Airport, Liverpool, L24 1YD",
    vehicle: {
      name: "Economy Taxi",
      passengers: 3,
      luggage: 2,
      image: "/ride-history-car.png",
      reviewStars: 3,
    },
    status: "Pending",
    // status: "Completed",
  },
  {
    date: "22 May 2024",
    time: "07:45",
    price: "320 £",
    from: "Edinburgh Waverley Station, Edinburgh, EH1 1BB",
    to: "Glasgow International Airport, Paisley, PA3 2SW",
    vehicle: {
      name: "Luxury Taxi",
      passengers: 5,
      luggage: 4,
      image: "/ride-history-car.png",
      reviewStars: 5,
    },
    returnSchedule: {
      date: "23 May 2024",
      time: "18:30",
    },
    status: "Completed",
  },
  {
    date: "10 June 2024",
    time: "08:00",
    price: "500 £",
    from: "Oxford Street, London, W1D 1BS",
    to: "Gatwick Airport, Horley, RH6 0NP",
    vehicle: {
      name: "SUV",
      passengers: 6,
      luggage: 5,
      image: "/ride-history-car.png",
      reviewStars: 4,
    },
    returnSchedule: {
      date: "11 June 2024",
      time: "19:00",
    },
    status: "Completed",
  },
  {
    date: "18 July 2024",
    time: "09:30",
    price: "410 £",
    from: "Bristol Temple Meads Station, Bristol, BS1 6QF",
    to: "Cardiff Airport, Barry, CF62 3BD",
    vehicle: {
      name: "Economy Taxi",
      passengers: 4,
      luggage: 2,
      image: "/ride-history-car.png",
      reviewStars: 4,
    },
    status: "Completed",
  },
  {
    date: "02 August 2024",
    time: "13:45",
    price: "290 £",
    from: "Leeds Station, Leeds, LS1 4DY",
    to: "Leeds Bradford Airport, Yeadon, LS19 7TU,",
    vehicle: {
      name: "Standard Taxi",
      passengers: 4,
      luggage: 3,
      image: "/ride-history-car.png",
      reviewStars: 4,
    },
    returnSchedule: {
      date: "03 August 2024",
      time: "16:00",
    },
    status: "Completed",
  },
];
